/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:48a6362b-0b1f-4383-8dbf-0b211710e1cc",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_Fuj8Audgw",
    "aws_user_pools_web_client_id": "2d37bn2ogr9uvjl721lgqd06s4",
    "oauth": {}
};


export default awsmobile;
