/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-2",
    "aws_cognito_identity_pool_id": "us-east-2:496284f3-5b6e-4ad2-b1c6-319168d0d704",
    "aws_cognito_region": "us-east-2",
    "aws_user_pools_id": "us-east-2_X1JjcuCeN",
    "aws_user_pools_web_client_id": "f00pt0p4ciea7grn7m1onrlp1",
    "oauth": {}
};


export default awsmobile;
