/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-2",
    "aws_cognito_identity_pool_id": "us-east-2:7260e781-0621-4f80-ada3-b8115686fd2b",
    "aws_cognito_region": "us-east-2",
    "aws_user_pools_id": "us-east-2_BaI3B16or",
    "aws_user_pools_web_client_id": "3ml60dguum6oav2vuc2om8sm35",
    "oauth": {}
};


export default awsmobile;
